import express from "express";
import { signup } from "../controllers/authenticationControllers/signup";
import { updateUser } from "../controllers/authenticationControllers/updateUser";
import { idValid } from "../middlewares/authMiddleware/idValid";
import { signin } from "../controllers/authenticationControllers/signin";
import { userExist } from "../middlewares/authMiddleware/userExist";
import { userNotExist } from "../middlewares/authMiddleware/userNotExist";
export const userRouter = express.Router();
userRouter.post("/", userNotExist, signup);
userRouter.put("/", idValid, updateUser);
userRouter.post("/signin", userExist, signin);
